language: C
compiler: clang
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.3
xcode_project: Assignment.xcodeproj # path to your xcodeproj folder
xcode_scheme: AssignmentTests
xcode_destination: platform=macOS
before_script: cd Assignment
#osx_image: xode10.1
#xcode_project: Assignment.xcodeproj
#xcode_scheme: Assignment
 
