language: c
install: make get-deps
compiler:
  - clang
  - gcc
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
     - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"