language: C
compiler: clang
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.3
before_script: cd Assignment
xcode_project: Assignment.xcodeproj # path to your xcodeproj folder
xcode_scheme: Assignment
xcode_destination: platform=macOS
build: cc main.c fileLoader.c textManipulation.c mylib.c graphics.c titleScreen.c gameScreen.c displayText.c
#osx_image: xode10.1
#xcode_project: Assignment.xcodeproj
#xcode_scheme: Assignment
 
